source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'TraceLog-iOS', :exclusive => true do
   platform :ios, '8.0'
    
   pod "TraceLog/Objc", :path => "../"
end

target 'TraceLog-iOS-Tests', :exclusive => true do
   platform :ios, '8.0'
  
   pod "TraceLog/Objc", :path => "../"
end

target 'TraceLog-OSX', :exclusive => true do
   platform :osx, '10.10'
  
   pod "TraceLog/Swift", :path => "../"
end

target 'TraceLog-OSX-Tests', :exclusive => true do
   platform :osx, '10.10'
    
   pod "TraceLog/Swift", :path => "../"
end
