source 'https://github.com/CocoaPods/Specs.git'
source 'ssh://git@stash.ci.climatedna.net:7999/mob/climate-cocoapods-specs.git'

use_frameworks!

target 'TraceLog', :exclusive => true do
  pod "TraceLog", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "TraceLog", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end
