source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'TraceLog', :exclusive => true do
  pod "TraceLog/Objc", :path => "../"
  pod "TraceLog/Swift", :path => "../"
end

target 'Tests', :exclusive => true do
    pod "TraceLog/Objc", :path => "../"
    pod "TraceLog/Swift", :path => "../"
end
