#if !canImport(ObjectiveC)
import XCTest

extension AnyReaderTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AnyReaderTests = [
        ("test_AnyReaderBase", test_AnyReaderBase),
        ("test_AnyReaderBox", test_AnyReaderBox),
    ]
}

extension TestHarnessTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TestHarnessTests = [
        ("testLogForError", testLogForError),
        ("testLogForInfo", testLogForInfo),
        ("testLogForTrace1", testLogForTrace1),
        ("testLogForTrace2", testLogForTrace2),
        ("testLogForTrace3", testLogForTrace3),
        ("testLogForTrace4", testLogForTrace4),
        ("testLogForWarning", testLogForWarning),
        ("testLogTestBlockForError", testLogTestBlockForError),
        ("testLogTestBlockForInfo", testLogTestBlockForInfo),
        ("testLogTestBlockForTrace1", testLogTestBlockForTrace1),
        ("testLogTestBlockForTrace2", testLogTestBlockForTrace2),
        ("testLogTestBlockForTrace3", testLogTestBlockForTrace3),
        ("testLogTestBlockForTrace4", testLogTestBlockForTrace4),
        ("testLogTestBlockForWarning", testLogTestBlockForWarning),
        ("testLogTestBlockWithCustomFile", testLogTestBlockWithCustomFile),
        ("testLogTestBlockWithCustomFunction", testLogTestBlockWithCustomFunction),
        ("testLogTestBlockWithCustomLine", testLogTestBlockWithCustomLine),
        ("testLogTestBlockWithCustomMessage", testLogTestBlockWithCustomMessage),
        ("testLogTestBlockWithCustomTag", testLogTestBlockWithCustomTag),
        ("testLogWithCustomFile", testLogWithCustomFile),
        ("testLogWithCustomFunction", testLogWithCustomFunction),
        ("testLogWithCustomLine", testLogWithCustomLine),
        ("testLogWithCustomMessage", testLogWithCustomMessage),
        ("testLogWithCustomTag", testLogWithCustomTag),
    ]
}

extension TestUtilitiesTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TestUtilitiesTests = [
        ("testShell", testShell),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(AnyReaderTests.__allTests__AnyReaderTests),
        testCase(TestHarnessTests.__allTests__TestHarnessTests),
        testCase(TestUtilitiesTests.__allTests__TestUtilitiesTests),
    ]
}
#endif
