#if !canImport(ObjectiveC)
import XCTest

extension ConfigurationTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ConfigurationTests = [
        ("testInit", testInit),
        ("testLoad_Prefixes", testLoad_Prefixes),
        ("testLoad_Tags", testLoad_Tags),
        ("testLogLevel_All_Default", testLogLevel_All_Default),
        ("testLogLevel_All_Set", testLogLevel_All_Set),
        ("testLogLevel_All_Set_Error", testLogLevel_All_Set_Error),
        ("testLogLevel_All_Set_Info", testLogLevel_All_Set_Info),
        ("testLogLevel_All_Set_InvalidLevel", testLogLevel_All_Set_InvalidLevel),
        ("testLogLevel_All_Set_Off", testLogLevel_All_Set_Off),
        ("testLogLevel_All_Set_Trace1", testLogLevel_All_Set_Trace1),
        ("testLogLevel_All_Set_Trace2", testLogLevel_All_Set_Trace2),
        ("testLogLevel_All_Set_Trace3", testLogLevel_All_Set_Trace3),
        ("testLogLevel_All_Set_Trace4", testLogLevel_All_Set_Trace4),
        ("testLogLevel_All_Set_Warning", testLogLevel_All_Set_Warning),
        ("testLogLevel_Prefix", testLogLevel_Prefix),
        ("testLogLevel_Tag", testLogLevel_Tag),
    ]
}

extension ConsoleWriterTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ConsoleWriterTests = [
        ("testLogError", testLogError),
        ("testLogInfo", testLogInfo),
        ("testLogTrace1", testLogTrace1),
        ("testLogTrace2", testLogTrace2),
        ("testLogTrace3", testLogTrace3),
        ("testLogTrace4", testLogTrace4),
        ("testLogWarning", testLogWarning),
    ]
}

extension EnvironmentTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__EnvironmentTests = [
        ("testInit", testInit),
        ("testInit_CollectionType", testInit_CollectionType),
        ("testInit_DictionaryLiteral", testInit_DictionaryLiteral),
        ("testSubscript", testSubscript),
    ]
}

extension FileWriterInternalsTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FileWriterInternalsTests = [
        ("testOpen", testOpen),
        ("testOpenCreatingDirectory", testOpenCreatingDirectory),
        ("testOpenFailure", testOpenFailure),
        ("testRotate", testRotate),
        ("testRotateFailure", testRotateFailure),
    ]
}

extension FileWriterTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FileWriterTests = [
        ("testErrorCreateFailedDescription", testErrorCreateFailedDescription),
        ("testErrorFileDoesNotExistDescription", testErrorFileDoesNotExistDescription),
        ("testLogError", testLogError),
        ("testLogInfo", testLogInfo),
        ("testLogTrace1", testLogTrace1),
        ("testLogTrace2", testLogTrace2),
        ("testLogTrace3", testLogTrace3),
        ("testLogTrace4", testLogTrace4),
        ("testLogWarning", testLogWarning),
        ("testRotationOnInit", testRotationOnInit),
        ("testRotationOnWrite", testRotationOnWrite),
    ]
}

extension MutexTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MutexTests = [
        ("testLockBlocked", testLockBlocked),
        ("testLockUnlock", testLockUnlock),
        ("testLockUnlockNonRecursiveBlocked", testLockUnlockNonRecursiveBlocked),
        ("testLockUnlockRecursive", testLockUnlockRecursive),
        ("testTryLockBlocked", testTryLockBlocked),
    ]
}

extension RuntimeContextTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RuntimeContextTests = [
        ("testDescription", testDescription),
    ]
}

extension StaticContextTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__StaticContextTests = [
        ("testDescription", testDescription),
    ]
}

extension TextFormatTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TextFormatTests = [
        ("testControlCharactersAbsentLeavesTheCharacters", testControlCharactersAbsentLeavesTheCharacters),
        ("testControlCharactersEscapeActuallyEscapes", testControlCharactersEscapeActuallyEscapes),
        ("testControlCharactersStripActuallyStrips", testControlCharactersStripActuallyStrips),
        ("testInitWithDateFormatter", testInitWithDateFormatter),
        ("testInitWithNoParameters", testInitWithNoParameters),
        ("testInitWithStripControlCharacters", testInitWithStripControlCharacters),
        ("testInitWithStripControlCharactersAndDateFormatter", testInitWithStripControlCharactersAndDateFormatter),
        ("testInitWithTemplate", testInitWithTemplate),
        ("testInitWithTerminator", testInitWithTerminator),
        ("testTemplateAllConstants", testTemplateAllConstants),
        ("testTemplateConstantsArePassedThrough", testTemplateConstantsArePassedThrough),
        ("testTemplateDate", testTemplateDate),
        ("testTemplateDefault", testTemplateDefault),
        ("testTemplateDoubleWrappedVariable", testTemplateDoubleWrappedVariable),
        ("testTemplateFile", testTemplateFile),
        ("testTemplateFunction", testTemplateFunction),
        ("testTemplateIncorrectVariables", testTemplateIncorrectVariables),
        ("testTemplateLevel", testTemplateLevel),
        ("testTemplateLine", testTemplateLine),
        ("testTemplateMessage", testTemplateMessage),
        ("testTemplateMessageWithEmbeddedMessageVariable", testTemplateMessageWithEmbeddedMessageVariable),
        ("testTemplateMessageWithEmbeddedVaraibles", testTemplateMessageWithEmbeddedVaraibles),
        ("testTemplateMessageWithEmbeddedVaraiblesReversed", testTemplateMessageWithEmbeddedVaraiblesReversed),
        ("testTemplateMultipleDate", testTemplateMultipleDate),
        ("testTemplateMultipleFile", testTemplateMultipleFile),
        ("testTemplateMultipleFunction", testTemplateMultipleFunction),
        ("testTemplateMultipleLevel", testTemplateMultipleLevel),
        ("testTemplateMultipleLine", testTemplateMultipleLine),
        ("testTemplateMultipleMessage", testTemplateMultipleMessage),
        ("testTemplateMultipleProcessIdentifier", testTemplateMultipleProcessIdentifier),
        ("testTemplateMultipleProcessName", testTemplateMultipleProcessName),
        ("testTemplateMultipleTag", testTemplateMultipleTag),
        ("testTemplateMultipleThreadIdentifier", testTemplateMultipleThreadIdentifier),
        ("testTemplateMultipleTimestamp", testTemplateMultipleTimestamp),
        ("testTemplateProcessIdentifier", testTemplateProcessIdentifier),
        ("testTemplateProcessName", testTemplateProcessName),
        ("testTemplateTag", testTemplateTag),
        ("testTemplateThreadIdentifier", testTemplateThreadIdentifier),
        ("testTemplateTimestamp", testTemplateTimestamp),
        ("testTemplateWithAllVariables", testTemplateWithAllVariables),
        ("testTemplateWithTabDeliminited", testTemplateWithTabDeliminited),
        ("testTerminatorCanBeSet", testTerminatorCanBeSet),
    ]
}

extension TraceLogPerformanceTestsSwift {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TraceLogPerformanceTestsSwift = [
        ("testLogErrorPerformance_NullWriter", testLogErrorPerformance_NullWriter),
        ("testLogTrace4Performance_NullWriter", testLogTrace4Performance_NullWriter),
    ]
}

extension TraceLogTestsSwift {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TraceLogTestsSwift = [
        ("testConfigureWithLogWriters", testConfigureWithLogWriters),
        ("testConfigureWithLogWritersAndEnvironment", testConfigureWithLogWritersAndEnvironment),
        ("testConfigureWithLogWritersAndEnvironmentGlobalInvalidLogLevel", testConfigureWithLogWritersAndEnvironmentGlobalInvalidLogLevel),
        ("testConfigureWithLogWritersAndEnvironmentPrefixInvalidLogLevel", testConfigureWithLogWritersAndEnvironmentPrefixInvalidLogLevel),
        ("testConfigureWithLogWritersAndEnvironmentTagInvalidLogLevel", testConfigureWithLogWritersAndEnvironmentTagInvalidLogLevel),
        ("testConfigureWithNoArgs", testConfigureWithNoArgs),
        ("testLogError", testLogError),
        ("testLogErrorWhileOff", testLogErrorWhileOff),
        ("testLogInfo", testLogInfo),
        ("testLogInfoWhileOff", testLogInfoWhileOff),
        ("testLogTrace", testLogTrace),
        ("testLogTrace1", testLogTrace1),
        ("testLogTrace1WhileOff", testLogTrace1WhileOff),
        ("testLogTrace2", testLogTrace2),
        ("testLogTrace2WhileOff", testLogTrace2WhileOff),
        ("testLogTrace3", testLogTrace3),
        ("testLogTrace3WhileOff", testLogTrace3WhileOff),
        ("testLogTrace4", testLogTrace4),
        ("testLogTrace4WhileOff", testLogTrace4WhileOff),
        ("testLogTraceWhileOff", testLogTraceWhileOff),
        ("testLogWarning", testLogWarning),
        ("testLogWarningWhileOff", testLogWarningWhileOff),
        ("testModeAsyncIsDifferentThread", testModeAsyncIsDifferentThread),
        ("testModeDirectIsSameThread", testModeDirectIsSameThread),
        ("testModeSyncBlocks", testModeSyncBlocks),
        ("testNoDeadLockAsyncMode", testNoDeadLockAsyncMode),
        ("testNoDeadLockDirectMode", testNoDeadLockDirectMode),
        ("testNoDeadLockSyncMode", testNoDeadLockSyncMode),
    ]
}

extension TraceLogWithFileWriterTests {
    // DO NOT MODIFY: This is autogenerated, use: 
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TraceLogWithFileWriterTests = [
        ("testLogError", testLogError),
        ("testLogInfo", testLogInfo),
        ("testLogTrace1", testLogTrace1),
        ("testLogTrace2", testLogTrace2),
        ("testLogTrace3", testLogTrace3),
        ("testLogTrace4", testLogTrace4),
        ("testLogWarning", testLogWarning),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ConfigurationTests.__allTests__ConfigurationTests),
        testCase(ConsoleWriterTests.__allTests__ConsoleWriterTests),
        testCase(EnvironmentTests.__allTests__EnvironmentTests),
        testCase(FileWriterInternalsTests.__allTests__FileWriterInternalsTests),
        testCase(FileWriterTests.__allTests__FileWriterTests),
        testCase(MutexTests.__allTests__MutexTests),
        testCase(RuntimeContextTests.__allTests__RuntimeContextTests),
        testCase(StaticContextTests.__allTests__StaticContextTests),
        testCase(TextFormatTests.__allTests__TextFormatTests),
        testCase(TraceLogPerformanceTestsSwift.__allTests__TraceLogPerformanceTestsSwift),
        testCase(TraceLogTestsSwift.__allTests__TraceLogTestsSwift),
        testCase(TraceLogWithFileWriterTests.__allTests__TraceLogWithFileWriterTests),
    ]
}
#endif
